CIRCUITPY_WIFI_SSID="BobsHauntedGecko"
CIRCUITPY_WIFI_PASSWORD="tkgr6073"
CIRCUITPY_WEB_API_PASSWORD="isogecko"
CIRCUITPY_WEB_INSTANCE_NAME="iso-lcd"
CIRCUITPY_WEB_TEXT_EDITOR=True
CIRCUITPY_WEB_FILE_MANAGER=True

# Backlight schedule (weekday/weekend)
BACKLIGHT_WEEKDAY_ON="07:30"
BACKLIGHT_WEEKDAY_OFF="22:00"
BACKLIGHT_WEEKEND_ON="10:00"
BACKLIGHT_WEEKEND_OFF="22:00"
