CIRCUITPY_WIFI_SSID="BobsHauntedGecko"
CIRCUITPY_WIFI_PASSWORD="tkgr6073"
CIRCUITPY_WEB_API_PASSWORD="isogecko"
CIRCUITPY_WEB_INSTANCE_NAME="iso-lcd"
CIRCUITPY_WEB_TEXT_EDITOR=True
CIRCUITPY_WEB_FILE_MANAGER=True

TEST_MODE=0
